### ISSUE TITLE
A suggets about 

### ISSUE THREAD

**Issue by MMarck** [iamm3chanic/TelegramBot#3]
Hello, I am sure that it can greatly improve the understanding of its code refracting the following variables in a document, help you a lot at the time of making changes to these values
![image](https://user-images.githubusercontent.com/53459069/104872398-cb04a380-591b-11eb-82d9-28af6b2f8ff9.png)

**Comment by iamm3chanic** [comment]
Thank You, that's an obviously good idea!

**Comment by iamm3chanic** [comment]
Done :)  
[Add CONSTANTS.java](https://github.com/iamm3chanic/TelegramBot/commit/d15915ea92fb5f9393173404870ec467dc979033)
